"use client";

import { useState } from "react";
import { configGroups } from "../lib/autoexecOptions";

export default function AutoexecBuilder() {

  const [activeIds, setActiveIds] = useState<string[]>([
    "fps",
    "music",
    "radar_zoom"
  ]);

  const [copied, setCopied] = useState(false);

  const toggle = (id: string) => {
    setActiveIds(prev =>
      prev.includes(id)
        ? prev.filter(i => i !== id)
        : [...prev, id]
    );
  };

  const generateCode = () => {

    const header =
      `// Autoexec generated by Aldento Hub - ${new Date().toLocaleDateString()}\n`;

    const selectedCmds = configGroups
      .flatMap(g => g.options)
      .filter(o => activeIds.includes(o.id))
      .map(o => o.cmd);

    return [
      header,
      ...selectedCmds,
      "host_writeconfig",
      'echo "[Autoexec] Zaladowano poprawnie!"'
    ].join("\n");

  };

  const copyToClipboard = () => {

    navigator.clipboard.writeText(generateCode());

    setCopied(true);

    setTimeout(() => {
      setCopied(false);
    }, 2000);

  };

  return (

    <div className="relative min-h-screen w-full overflow-hidden flex items-center justify-center p-4 md:p-8">

      <div className="bg-layers" />
      <div className="bg-grid absolute inset-0 z-[-1]" />
      <div className="bg-noise absolute inset-0 z-[-1]" />

      <div className="light-blob top-[-10%] left-[-10%]" />
      <div className="light-blob bottom-[-10%] right-[-10%] [animation-delay:2s]" />

      <div className="w-full max-w-6xl flex flex-col gap-6">

        {/* HEADER */}

        <div className="flex items-center justify-between px-2">

          <div className="flex items-center gap-3">

            <div className="w-8 h-8 rounded-lg bg-accent shadow-[0_0_15px_var(--color-accent-glow)] flex items-center justify-center font-black italic">
              A
            </div>

            <span className="text-xs font-mono tracking-[0.3em] text-white/60 uppercase">
              Autoexec Builder
            </span>

          </div>

        </div>

        {/* OPTIONS */}

        <div className="grid md:grid-cols-2 gap-6">

          {configGroups.map(group => (

            <div
              key={group.name}
              className="glass-card rounded-3xl p-6"
            >

              <h3 className="text-xs font-bold text-white/50 uppercase tracking-widest mb-4">
                {group.name}
              </h3>

              <div className="space-y-2">

                {group.options.map(opt => {

                  const active = activeIds.includes(opt.id);

                  return (

                    <button
                      key={opt.id}
                      onClick={() => toggle(opt.id)}

className={`w-full text-left p-4 rounded-xl border border-white/5 transition-colors duration-150

${active
  ? "border-accent bg-[rgba(94,106,210,0.08)]"
  : "hover:border-white/10 bg-white/[0.01]"
}
`}
                    >

                      <div className="flex justify-between items-center mb-1">

                        <span className="font-semibold text-sm">
                          {opt.label}
                        </span>

                        <div
                          className={`w-2 h-2 rounded-full
                          ${active
                            ? "bg-accent shadow-[0_0_8px_var(--color-accent-glow)]"
                            : "bg-white/20"
                          }`}
                        />

                      </div>

                      <p className="text-[11px] text-white/40 leading-tight">
                        {opt.desc}
                      </p>

                    </button>

                  );

                })}

              </div>

            </div>

          ))}

        </div>

        {/* PREVIEW */}

        <div className="glass-card rounded-3xl p-4 font-mono text-xs text-green-400 overflow-hidden h-[260px]">

          <pre className="whitespace-pre overflow-x-auto opacity-80 max-h-[260px]">
{generateCode()}
          </pre>

        </div>

        {/* COPY BUTTON */}

        <button

          onClick={copyToClipboard}

          className={`w-full py-4 rounded-2xl font-bold uppercase tracking-wide transition-colors

          ${copied
            ? "bg-green-500 text-black"
            : "bg-accent text-white hover:bg-[rgba(94,106,210,0.85)]"
          }`}

        >

          {copied
            ? "SKOPIOWANO AUTOEXEC"
            : "KOPIUJ AUTOEXEC"}

        </button>

      </div>

    </div>

  );

}