"use client";
import { useState } from "react";

// Definicja opcji na podstawie Twojego pliku
const configGroups = [
  {
    name: "Audio & Performance",
    options: [
      { id: "music", label: "Music (10s Warning only)", cmd: 'snd_deathcamera_volume "0"; snd_mapobjective_volume "0"; snd_menumusic_volume "0"; snd_roundend_volume "0"; snd_roundstart_volume "0"; snd_tensecondwarning_volume "0.05"', desc: "Wycisza wszystko poza bombą (10s)." },
      { id: "fps", label: "Uncapped FPS + UI Limit", cmd: 'fps_max "0"; fps_max_ui "64"', desc: "Max FPS w grze, oszczędność w menu." },
      { id: "network", label: "Pro Network (Rate & Interp)", cmd: 'rate "786432"; cl_interp_ratio "0"', desc: "Najlepsze ustawienia pod stabilne łącze." },
      { id: "latency", label: "Low Latency Sleep", cmd: 'engine_low_latency_sleep_after_client_tick "1"', desc: "Minimalizuje opóźnienia silnika." },
      { id: "predict", label: "Disable FX Prediction", cmd: 'cl_predict_kill_ragdolls "false"; cl_predict_head_shot_fx "false"; cl_predict_body_shot_fx "false"', desc: "Wyłącza przewidywanie efektów dla lepszego feelingu." },
    ]
  },
  {
    name: "Radar & HUD",
    options: [
      { id: "radar_zoom", label: "Pro Radar (More Info)", cmd: 'cl_radar_always_centered "1"; cl_radar_scale "0.3"; cl_radar_icon_scale_min "0.6"; cl_radar_scale_dynamic "true"', desc: "Widzisz więcej mapy na radarze." },
      { id: "clean_hud", label: "Clean HUD", cmd: 'r_show_build_info "false"; cl_hide_avatar_images "2"', desc: "Usuwa zbędne napisy i avatary." },
      { id: "teammates", label: "Teammate Overhead Fade", cmd: 'cl_teamid_overhead_fade_near_crosshair "1"', desc: "Nicki nie zasłaniają przeciwnika." },
    ]
  },
  {
    name: "Binds & Misc",
    options: [
      { id: "jump_scroll", label: "Jump on Scroll", cmd: 'bind "mwheelup" "+jump"; bind "mwheeldown" "+jump"; bind "space" "+jump"', desc: "Skakanie scrollem i spacją." },
      { id: "no_e_buy", label: "Disable E to Buy", cmd: 'cl_use_opens_buy_menu "0"', desc: "E nie otwiera menu zakupów." },
      { id: "mute_focus", label: "Sound on Alt-Tab", cmd: 'snd_mute_losefocus "0"', desc: "Słyszysz grę po zminimalizowaniu." },
    ]
  }
];

export default function AutoexecBuilder() {
  const [activeIds, setActiveIds] = useState<string[]>(["fps", "music", "radar_zoom"]);
  const [copied, setCopied] = useState(false);

  const toggle = (id: string) => {
    setActiveIds(prev => prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]);
  };

  const generateCode = () => {
    const header = `// Autoexec generated by Aldento Hub - ${new Date().toLocaleDateString()}\n`;
    const selectedCmds = configGroups
      .flatMap(g => g.options)
      .filter(o => activeIds.includes(o.id))
      .map(o => o.cmd);
    
    return [header, ...selectedCmds, "host_writeconfig", 'echo "[Autoexec] Zaladowano poprawnie!"'].join("\n");
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="w-full max-w-lg mx-auto p-4 bg-black text-white min-h-screen">
      <div className="mb-8 text-center pt-6">
        <h1 className="text-3xl font-black italic tracking-tighter text-orange-500 uppercase">Config Builder</h1>
        <p className="text-gray-500 text-xs">By Aldento - Optymalizacja CS2</p>
      </div>

      <div className="space-y-8 mb-24">
        {configGroups.map(group => (
          <div key={group.name}>
            <h3 className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-3 px-2">{group.name}</h3>
            <div className="grid grid-cols-1 gap-2">
              {group.options.map(opt => (
                <div 
                  key={opt.id}
                  onClick={() => toggle(opt.id)}
                  className={`p-4 rounded-2xl border-2 transition-all cursor-pointer ${
                    activeIds.includes(opt.id) ? 'border-orange-500 bg-orange-500/10' : 'border-gray-800 bg-gray-900/50'
                  }`}
                >
                  <div className="flex justify-between items-center mb-1">
                    <span className="font-bold text-sm">{opt.label}</span>
                    <div className={`w-2 h-2 rounded-full ${activeIds.includes(opt.id) ? 'bg-orange-500 animate-pulse' : 'bg-gray-700'}`} />
                  </div>
                  <p className="text-[10px] text-gray-500 leading-tight">{opt.desc}</p>
                </div>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* Floating Copy Button */}
      <div className="fixed bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-black via-black to-transparent">
        <div className="max-w-lg mx-auto">
            <div className="bg-gray-900 border border-gray-800 p-3 rounded-t-2xl mb-2 overflow-hidden">
                <p className="text-[10px] font-mono text-green-500 truncate">{generateCode().split('\n')[1] || '...'}</p>
            </div>
            <button 
                onClick={copyToClipboard}
                className={`w-full py-5 rounded-2xl font-black uppercase transition-all active:scale-95 ${
                    copied ? 'bg-green-500 text-black' : 'bg-orange-500 text-white shadow-lg shadow-orange-500/20'
                }`}
            >
                {copied ? "SKOPIOWANO!" : "SKOPIUJ CALY AUTOEXEC"}
            </button>
        </div>
      </div>
    </div>
  );
}